### ISSUE TITLE
插件兼容问题

### ISSUE THREAD

**Issue by HippocampalAbnormality** [itouzigithub/experience-mobile#10]
移动端 ajax 库建议用 zepto，如用vue-resource.js或者axios.js，注意以下两个问题：

- ES6新接口promise不兼容安卓4.2及以下版本请添加 polyfill。[参考](https://github.com/mzabriskie/axios)
- ArrayBuffer构造函数，ES5就出现了，但是安卓4.4.2不支持（查了axios与zepto的源码，后者不包含ArrayBuffer接口，从目前来看，只要系统不兼容此构造函数，使用axios就会报错）。

#### 结论：
现阶段出于兼容性考虑，不推荐使用axios。
相对而言，vue-resource虽然也有promise问题，但却没有ArraybBuffer问题，现阶段可用。

**Comment by bison1994** [comment]
使用插件时，就应该弄清楚该插件的兼容性，所以没有必要单独整理出来
